FROM		openjdk:13-jdk-alpine

MAINTAINER 	ihsanch sanchezih@gmail.com

COPY		./holamundo-springboot/target/holamundo-springboot-1.0.0.jar /app/holamundo-springboot-1.0.0.jar

ENTRYPOINT	["java", "-jar", "/app/holamundo-springboot-1.0.0.jar"]