
package com.github.sanchezih.cxf.src.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.2
 * Mon Jun 06 12:47:20 ART 2022
 * Generated source version: 3.5.2
 */

@XmlRootElement(name = "addPersona", namespace = "http://src.cxf.sanchezih.github.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addPersona", namespace = "http://src.cxf.sanchezih.github.com/")

public class AddPersona {

    @XmlElement(name = "arg0")
    private com.github.sanchezih.cxf.src.Persona arg0;

    public com.github.sanchezih.cxf.src.Persona getArg0() {
        return this.arg0;
    }

    public void setArg0(com.github.sanchezih.cxf.src.Persona newArg0)  {
        this.arg0 = newArg0;
    }

}

