
package com.github.sanchezih.cxf.src.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.2
 * Mon Jun 06 12:47:20 ART 2022
 * Generated source version: 3.5.2
 */

@XmlRootElement(name = "getPersonaResponse", namespace = "http://src.cxf.sanchezih.github.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getPersonaResponse", namespace = "http://src.cxf.sanchezih.github.com/")

public class GetPersonaResponse {

    @XmlElement(name = "return")
    private com.github.sanchezih.cxf.src.Persona _return;

    public com.github.sanchezih.cxf.src.Persona getReturn() {
        return this._return;
    }

    public void setReturn(com.github.sanchezih.cxf.src.Persona new_return)  {
        this._return = new_return;
    }

}

