
package com.github.sanchezih.cxf.src.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.2
 * Mon Jun 06 12:47:20 ART 2022
 * Generated source version: 3.5.2
 */

@XmlRootElement(name = "getPersonas", namespace = "http://src.cxf.sanchezih.github.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getPersonas", namespace = "http://src.cxf.sanchezih.github.com/")

public class GetPersonas {


}

